name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
      full-test:
        runs-on: self-hosted
        steps:
          # 1. Access the workspace repository without cleaning out existing files
          - uses: actions/checkout@v3
            with:
              clean: false
              submodules: 'recursive'
              
          # 2. Run the tests directly using your existing build artifacts
          - name: Run full test
            timeout-minutes: 15
            run: |
               docker run --rm \
                 -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} \
                 -v /home/artb/git/assignment-9-yocto/build:/home/artb/git/assignment-9-yocto/build \
                 --workdir=${GITHUB_WORKSPACE} \
                 cuaesd/aesd-autotest:assignment9-yocto \
                 ./full-test.sh
